/* DROP DATABASE BD_Transporte */

CREATE DATABASE BD_Transporte
GO
USE BD_Transporte
GO

CREATE TABLE PASAJERO (
    COD_PASJ int  NOT NULL IDENTITY(1,1),
	NOM_PASJ varchar(200)  NOT NULL,
    DNI_PASJ varchar(8)  NOT NULL,
    FECNAC_PASJ date  NOT NULL,
    CONSTRAINT PASAJERO_pk PRIMARY KEY  (COD_PASJ)
);
GO

CREATE TABLE BUS (
    COD_BUS int  NOT NULL IDENTITY(1,1),
	PLACA_BUS varchar(20)  NOT NULL,
    NASIENTO varchar(2)  NOT NULL
    CONSTRAINT BUS_pk PRIMARY KEY  (COD_BUS)
);
GO

-- Table: RUTAS
CREATE TABLE RUTAS (
    COD_RUTA int  NOT NULL IDENTITY(1,1),
    NOM_RUTA VARCHAR(200) NOT NULL,
    COS_RUTA decimal(5,2)  NOT NULL,
    CONSTRAINT RUTAS_pk PRIMARY KEY  (COD_RUTA)
);
GO

-- Table: SUCURSAL
CREATE TABLE SUCURSAL (
    COD_SUC int  NOT NULL IDENTITY(1,1),
    NOM_SUC varchar(200)  NOT NULL,
    CONSTRAINT SUCURSAL_pk PRIMARY KEY  (COD_SUC)
);
GO

-- Table: VIAJE
CREATE TABLE VIAJE (
    COD_VIAJE int  NOT NULL IDENTITY(1,1),
    FEC_VIAJE date  NOT NULL,
    NUM_ASIE varchar(2)  NOT NULL,
    COD_PASJ int  NOT NULL,
    COD_RUTA int  NOT NULL,
	COD_BUS int  NOT NULL,
    CONSTRAINT VIAJE_pk PRIMARY KEY  (COD_VIAJE)
);
GO

INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ) VALUES('DANIEL QUISPE','76806031','01/31/2000');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ) VALUES('KARLA PEÑA','75852369','04/05/2000');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ) VALUES('ARMANDO CASAS','12536965','06/08/1999');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ) VALUES('PEPITO PEREZ','12365485','02/03/1997');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ) VALUES('GABRIELA RODRIGUEZ','75856965','04/05/1999');

INSERT INTO SUCURSAL(NOM_SUC) VALUES('LIMA');
INSERT INTO SUCURSAL(NOM_SUC) VALUES('CAÑETE');
INSERT INTO SUCURSAL(NOM_SUC) VALUES('CHINCHA');
INSERT INTO SUCURSAL(NOM_SUC) VALUES('PISCO');
INSERT INTO SUCURSAL(NOM_SUC) VALUES('ICA');

