/* DROP DATABASE BD_Transporte */

CREATE DATABASE BD_Transporte
GO
USE BD_Transporte
GO

CREATE TABLE BOLETO (
    COD_BOL int  NOT NULL IDENTITY,
    FEC_BOL date   NULL,
    NUM_ASIE varchar(2)   NULL,
    EST_BOL varchar(1)  NULL,
    COD_PASJ int  NOT NULL,
    COD_RUTA int  NOT NULL,
    COD_BUS int  NOT NULL,
    CONSTRAINT BOLETO_pk PRIMARY KEY  (COD_BOL)
);
GO

-- Table: BUS
CREATE TABLE BUS (
    COD_BUS int  NOT NULL IDENTITY,
    PLACA_BUS varchar(7)  NOT NULL,
    NASIENTO varchar(2)  NOT NULL,
    EST_BUS varchar(1) NOT NULL,
    CONSTRAINT BUS_pk PRIMARY KEY  (COD_BUS)
);
GO

-- Table: PASAJERO
CREATE TABLE PASAJERO (
    COD_PASJ int  NOT NULL IDENTITY,
    DNI_PASJ varchar(8)   NULL,
    FECNAC_PASJ date   NULL,
    NOM_PASJ varchar(200)   NULL,
    EST_PASJ varchar(1)  NULL,
    CONSTRAINT PASAJERO_pk PRIMARY KEY  (COD_PASJ)
);
GO

-- Table: RUTAS
CREATE TABLE RUTAS (
    COD_RUTA int  NOT NULL IDENTITY,
    ORI_RUTA varchar(200)   NULL,
    DES_RUTA varchar(200)   NULL,
    COS_RUTA varchar(2)   NULL,
    EST_RUTA varchar(1)  NULL,
    CONSTRAINT RUTAS_pk PRIMARY KEY  (COD_RUTA)
);
GO

-- Table: SUCURSALES
CREATE TABLE SUCURSALES (
    COD_SUC int  NOT NULL IDENTITY,
    NOM_SUC varchar(200)   NULL,
    EST_SUC varchar(1)  NULL,
    CONSTRAINT SUCURSALES_pk PRIMARY KEY  (COD_SUC)
);
GO

-- foreign keys
-- Reference: BOLETO_BUS (table: BOLETO)
ALTER TABLE BOLETO ADD CONSTRAINT BOLETO_BUS
    FOREIGN KEY (COD_BUS)
    REFERENCES BUS (COD_BUS);
GO

-- Reference: BOLETO_PASAJERO (table: BOLETO)
ALTER TABLE BOLETO ADD CONSTRAINT BOLETO_PASAJERO
    FOREIGN KEY (COD_PASJ)
    REFERENCES PASAJERO (COD_PASJ);
GO

-- Reference: BOLETO_RUTAS (table: BOLETO)
ALTER TABLE BOLETO ADD CONSTRAINT BOLETO_RUTAS
    FOREIGN KEY (COD_RUTA)
    REFERENCES RUTAS (COD_RUTA);
GO

INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ, EST_PASJ) VALUES('DANIEL QUISPE','76806031','01/31/2000','A');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ, EST_PASJ) VALUES('KARLA PEÑA','75852369','04/05/2000','A');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ, EST_PASJ) VALUES('ARMANDO CASAS','12536965','06/08/1999','A');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ, EST_PASJ) VALUES('PEPITO PEREZ','12365485','02/03/1997','A');
INSERT INTO PASAJERO(NOM_PASJ, DNI_PASJ, FECNAC_PASJ, EST_PASJ) VALUES('GABRIELA RODRIGUEZ','75856965','04/05/1999','A');

INSERT INTO SUCURSALES(NOM_SUC, EST_SUC) VALUES('LIMA','A');
INSERT INTO SUCURSALES(NOM_SUC, EST_SUC) VALUES('CAÑETE','A');
INSERT INTO SUCURSALES(NOM_SUC, EST_SUC) VALUES('CHINCHA','A');
INSERT INTO SUCURSALES(NOM_SUC, EST_SUC) VALUES('PISCO','A');
INSERT INTO SUCURSALES(NOM_SUC, EST_SUC) VALUES('ICA','A');

--end file
