USE BD_TRANSPORTE
GO
SELECT * FROM BOLETO
GO

/* MUESTRA A LOS PASAJEROS QUE VIEJARON CON SU RESPECTIVA FECHA DE VIAJE Y SU RUTA */
CREATE VIEW VW_BolPas
AS
    SELECT PASAJERO.NOM_PASJ, CONCAT(RUTAS.ORI_RUTA,'-',RUTAS.DES_RUTA) AS 'RUTA',FEC_BOL
    FROM BOLETO
    INNER JOIN PASAJERO ON PASAJERO.COD_PASJ = BOLETO.COD_PASJ
    INNER JOIN RUTAS ON RUTAS.COD_RUTA = BOLETO.COD_RUTA
GO

/* MUESTRA LOS PASAJEROS ACTIVOS */
CREATE VIEW VW_PasAct
AS
    SELECT NOM_PASJ
    FROM PASAJERO
    WHERE EST_PASJ LIKE 'A'
GO

/* MUESTRA LOS BUSES A LOS QUE SE SUBIERON LOS PASAJEROS PARA VIAJAR */
CREATE VIEW VW_PasBus
AS
    SELECT PASAJERO.NOM_PASJ,BUS.PLACA_BUS
    FROM BOLETO
    INNER JOIN PASAJERO ON PASAJERO.COD_PASJ = BOLETO.COD_PASJ
    INNER JOIN BUS ON BUS.COD_BUS = BOLETO.COD_BUS
GO

/* MUESTRA LOS DATOS ESPECÍFICOS DEL BOLETO */
CREATE VIEW VW_Boleto
AS
    SELECT COD_BOL, PASAJERO.NOM_PASJ,CONCAT(RUTAS.ORI_RUTA,'-',RUTAS.DES_RUTA) AS 'RUTA',BUS.PLACA_BUS, FEC_BOL
    FROM BOLETO
    INNER JOIN BUS ON BUS.COD_BUS = BOLETO.COD_BUS
    INNER JOIN RUTAS ON RUTAS.COD_RUTA = BOLETO.COD_RUTA
    INNER JOIN PASAJERO ON PASAJERO.COD_PASJ = BOLETO.COD_PASJ
GO
    